version: '3'
services:
  vps:
    build: .
    ports:
      - "2222:22"
      - "8080:8080"
    restart: always
    privileged: true
    mem_limit: 164g
    mem_reservation: 32g
    cpus: 16
    command: /usr/sbin/sshd -D -e
